.align 16
.text
.extern handle
.global table


entry0:
	pushq $0
	pushq $0
	jmp common
entry1:
	pushq $0
	pushq $1
	jmp common
entry2:
	pushq $0
	pushq $2
	jmp common
entry3:
	pushq $0
	pushq $3
	jmp common
entry4:
	pushq $0
	pushq $4
	jmp common
entry5:
	pushq $0
	pushq $5
	jmp common
entry6:
	pushq $0
	pushq $6
	jmp common
entry7:
	pushq $0
	pushq $7
	jmp common
entry8:
	pushq $8
	jmp common
entry9:
	pushq $0
	pushq $9
	jmp common
entry10:
	pushq $10
	jmp common
entry11:
	pushq $11
	jmp common
entry12:
	pushq $12
	jmp common
entry13:
	pushq $13
	jmp common
entry14:
	pushq $14
	jmp common
entry15:
	pushq $0
	pushq $15
	jmp common
entry16:
	pushq $0
	pushq $16
	jmp common
entry17:
	pushq $17
	jmp common
entry18:
	pushq $0
	pushq $18
	jmp common
entry19:
	pushq $0
	pushq $19
	jmp common
entry20:
	pushq $0
	pushq $20
	jmp common
entry21:
	pushq $0
	pushq $21
	jmp common
entry22:
	pushq $0
	pushq $22
	jmp common
entry23:
	pushq $0
	pushq $23
	jmp common
entry24:
	pushq $0
	pushq $24
	jmp common
entry25:
	pushq $0
	pushq $25
	jmp common
entry26:
	pushq $0
	pushq $26
	jmp common
entry27:
	pushq $0
	pushq $27
	jmp common
entry28:
	pushq $0
	pushq $28
	jmp common
entry29:
	pushq $0
	pushq $29
	jmp common
entry30:
	pushq $0
	pushq $30
	jmp common
entry31:
	pushq $0
	pushq $31
	jmp common
entry32:
	pushq $0
	pushq $32
	jmp common
entry33:
	pushq $0
	pushq $33
	jmp common
entry34:
	pushq $0
	pushq $34
	jmp common
entry35:
	pushq $0
	pushq $35
	jmp common
entry36:
	pushq $0
	pushq $36
	jmp common
entry37:
	pushq $0
	pushq $37
	jmp common
entry38:
	pushq $0
	pushq $38
	jmp common
entry39:
	pushq $0
	pushq $39
	jmp common
entry40:
	pushq $0
	pushq $40
	jmp common
entry41:
	pushq $0
	pushq $41
	jmp common
entry42:
	pushq $0
	pushq $42
	jmp common
entry43:
	pushq $0
	pushq $43
	jmp common
entry44:
	pushq $0
	pushq $44
	jmp common
entry45:
	pushq $0
	pushq $45
	jmp common
entry46:
	pushq $0
	pushq $46
	jmp common
entry47:
	pushq $0
	pushq $47
	jmp common
entry48:
	pushq $0
	pushq $48
	jmp common
entry49:
	pushq $0
	pushq $49
	jmp common
entry50:
	pushq $0
	pushq $50
	jmp common
entry51:
	pushq $0
	pushq $51
	jmp common
entry52:
	pushq $0
	pushq $52
	jmp common
entry53:
	pushq $0
	pushq $53
	jmp common
entry54:
	pushq $0
	pushq $54
	jmp common
entry55:
	pushq $0
	pushq $55
	jmp common
entry56:
	pushq $0
	pushq $56
	jmp common
entry57:
	pushq $0
	pushq $57
	jmp common
entry58:
	pushq $0
	pushq $58
	jmp common
entry59:
	pushq $0
	pushq $59
	jmp common
entry60:
	pushq $0
	pushq $60
	jmp common
entry61:
	pushq $0
	pushq $61
	jmp common
entry62:
	pushq $0
	pushq $62
	jmp common
entry63:
	pushq $0
	pushq $63
	jmp common
entry64:
	pushq $0
	pushq $64
	jmp common
entry65:
	pushq $0
	pushq $65
	jmp common
entry66:
	pushq $0
	pushq $66
	jmp common
entry67:
	pushq $0
	pushq $67
	jmp common
entry68:
	pushq $0
	pushq $68
	jmp common
entry69:
	pushq $0
	pushq $69
	jmp common
entry70:
	pushq $0
	pushq $70
	jmp common
entry71:
	pushq $0
	pushq $71
	jmp common
entry72:
	pushq $0
	pushq $72
	jmp common
entry73:
	pushq $0
	pushq $73
	jmp common
entry74:
	pushq $0
	pushq $74
	jmp common
entry75:
	pushq $0
	pushq $75
	jmp common
entry76:
	pushq $0
	pushq $76
	jmp common
entry77:
	pushq $0
	pushq $77
	jmp common
entry78:
	pushq $0
	pushq $78
	jmp common
entry79:
	pushq $0
	pushq $79
	jmp common
entry80:
	pushq $0
	pushq $80
	jmp common
entry81:
	pushq $0
	pushq $81
	jmp common
entry82:
	pushq $0
	pushq $82
	jmp common
entry83:
	pushq $0
	pushq $83
	jmp common
entry84:
	pushq $0
	pushq $84
	jmp common
entry85:
	pushq $0
	pushq $85
	jmp common
entry86:
	pushq $0
	pushq $86
	jmp common
entry87:
	pushq $0
	pushq $87
	jmp common
entry88:
	pushq $0
	pushq $88
	jmp common
entry89:
	pushq $0
	pushq $89
	jmp common
entry90:
	pushq $0
	pushq $90
	jmp common
entry91:
	pushq $0
	pushq $91
	jmp common
entry92:
	pushq $0
	pushq $92
	jmp common
entry93:
	pushq $0
	pushq $93
	jmp common
entry94:
	pushq $0
	pushq $94
	jmp common
entry95:
	pushq $0
	pushq $95
	jmp common
entry96:
	pushq $0
	pushq $96
	jmp common
entry97:
	pushq $0
	pushq $97
	jmp common
entry98:
	pushq $0
	pushq $98
	jmp common
entry99:
	pushq $0
	pushq $99
	jmp common
entry100:
	pushq $0
	pushq $100
	jmp common
entry101:
	pushq $0
	pushq $101
	jmp common
entry102:
	pushq $0
	pushq $102
	jmp common
entry103:
	pushq $0
	pushq $103
	jmp common
entry104:
	pushq $0
	pushq $104
	jmp common
entry105:
	pushq $0
	pushq $105
	jmp common
entry106:
	pushq $0
	pushq $106
	jmp common
entry107:
	pushq $0
	pushq $107
	jmp common
entry108:
	pushq $0
	pushq $108
	jmp common
entry109:
	pushq $0
	pushq $109
	jmp common
entry110:
	pushq $0
	pushq $110
	jmp common
entry111:
	pushq $0
	pushq $111
	jmp common
entry112:
	pushq $0
	pushq $112
	jmp common
entry113:
	pushq $0
	pushq $113
	jmp common
entry114:
	pushq $0
	pushq $114
	jmp common
entry115:
	pushq $0
	pushq $115
	jmp common
entry116:
	pushq $0
	pushq $116
	jmp common
entry117:
	pushq $0
	pushq $117
	jmp common
entry118:
	pushq $0
	pushq $118
	jmp common
entry119:
	pushq $0
	pushq $119
	jmp common
entry120:
	pushq $0
	pushq $120
	jmp common
entry121:
	pushq $0
	pushq $121
	jmp common
entry122:
	pushq $0
	pushq $122
	jmp common
entry123:
	pushq $0
	pushq $123
	jmp common
entry124:
	pushq $0
	pushq $124
	jmp common
entry125:
	pushq $0
	pushq $125
	jmp common
entry126:
	pushq $0
	pushq $126
	jmp common
entry127:
	pushq $0
	pushq $127
	jmp common
entry128:
	pushq $0
	pushq $128
	jmp common
entry129:
	pushq $0
	pushq $129
	jmp common
entry130:
	pushq $0
	pushq $130
	jmp common
entry131:
	pushq $0
	pushq $131
	jmp common
entry132:
	pushq $0
	pushq $132
	jmp common
entry133:
	pushq $0
	pushq $133
	jmp common
entry134:
	pushq $0
	pushq $134
	jmp common
entry135:
	pushq $0
	pushq $135
	jmp common
entry136:
	pushq $0
	pushq $136
	jmp common
entry137:
	pushq $0
	pushq $137
	jmp common
entry138:
	pushq $0
	pushq $138
	jmp common
entry139:
	pushq $0
	pushq $139
	jmp common
entry140:
	pushq $0
	pushq $140
	jmp common
entry141:
	pushq $0
	pushq $141
	jmp common
entry142:
	pushq $0
	pushq $142
	jmp common
entry143:
	pushq $0
	pushq $143
	jmp common
entry144:
	pushq $0
	pushq $144
	jmp common
entry145:
	pushq $0
	pushq $145
	jmp common
entry146:
	pushq $0
	pushq $146
	jmp common
entry147:
	pushq $0
	pushq $147
	jmp common
entry148:
	pushq $0
	pushq $148
	jmp common
entry149:
	pushq $0
	pushq $149
	jmp common
entry150:
	pushq $0
	pushq $150
	jmp common
entry151:
	pushq $0
	pushq $151
	jmp common
entry152:
	pushq $0
	pushq $152
	jmp common
entry153:
	pushq $0
	pushq $153
	jmp common
entry154:
	pushq $0
	pushq $154
	jmp common
entry155:
	pushq $0
	pushq $155
	jmp common
entry156:
	pushq $0
	pushq $156
	jmp common
entry157:
	pushq $0
	pushq $157
	jmp common
entry158:
	pushq $0
	pushq $158
	jmp common
entry159:
	pushq $0
	pushq $159
	jmp common
entry160:
	pushq $0
	pushq $160
	jmp common
entry161:
	pushq $0
	pushq $161
	jmp common
entry162:
	pushq $0
	pushq $162
	jmp common
entry163:
	pushq $0
	pushq $163
	jmp common
entry164:
	pushq $0
	pushq $164
	jmp common
entry165:
	pushq $0
	pushq $165
	jmp common
entry166:
	pushq $0
	pushq $166
	jmp common
entry167:
	pushq $0
	pushq $167
	jmp common
entry168:
	pushq $0
	pushq $168
	jmp common
entry169:
	pushq $0
	pushq $169
	jmp common
entry170:
	pushq $0
	pushq $170
	jmp common
entry171:
	pushq $0
	pushq $171
	jmp common
entry172:
	pushq $0
	pushq $172
	jmp common
entry173:
	pushq $0
	pushq $173
	jmp common
entry174:
	pushq $0
	pushq $174
	jmp common
entry175:
	pushq $0
	pushq $175
	jmp common
entry176:
	pushq $0
	pushq $176
	jmp common
entry177:
	pushq $0
	pushq $177
	jmp common
entry178:
	pushq $0
	pushq $178
	jmp common
entry179:
	pushq $0
	pushq $179
	jmp common
entry180:
	pushq $0
	pushq $180
	jmp common
entry181:
	pushq $0
	pushq $181
	jmp common
entry182:
	pushq $0
	pushq $182
	jmp common
entry183:
	pushq $0
	pushq $183
	jmp common
entry184:
	pushq $0
	pushq $184
	jmp common
entry185:
	pushq $0
	pushq $185
	jmp common
entry186:
	pushq $0
	pushq $186
	jmp common
entry187:
	pushq $0
	pushq $187
	jmp common
entry188:
	pushq $0
	pushq $188
	jmp common
entry189:
	pushq $0
	pushq $189
	jmp common
entry190:
	pushq $0
	pushq $190
	jmp common
entry191:
	pushq $0
	pushq $191
	jmp common
entry192:
	pushq $0
	pushq $192
	jmp common
entry193:
	pushq $0
	pushq $193
	jmp common
entry194:
	pushq $0
	pushq $194
	jmp common
entry195:
	pushq $0
	pushq $195
	jmp common
entry196:
	pushq $0
	pushq $196
	jmp common
entry197:
	pushq $0
	pushq $197
	jmp common
entry198:
	pushq $0
	pushq $198
	jmp common
entry199:
	pushq $0
	pushq $199
	jmp common
entry200:
	pushq $0
	pushq $200
	jmp common
entry201:
	pushq $0
	pushq $201
	jmp common
entry202:
	pushq $0
	pushq $202
	jmp common
entry203:
	pushq $0
	pushq $203
	jmp common
entry204:
	pushq $0
	pushq $204
	jmp common
entry205:
	pushq $0
	pushq $205
	jmp common
entry206:
	pushq $0
	pushq $206
	jmp common
entry207:
	pushq $0
	pushq $207
	jmp common
entry208:
	pushq $0
	pushq $208
	jmp common
entry209:
	pushq $0
	pushq $209
	jmp common
entry210:
	pushq $0
	pushq $210
	jmp common
entry211:
	pushq $0
	pushq $211
	jmp common
entry212:
	pushq $0
	pushq $212
	jmp common
entry213:
	pushq $0
	pushq $213
	jmp common
entry214:
	pushq $0
	pushq $214
	jmp common
entry215:
	pushq $0
	pushq $215
	jmp common
entry216:
	pushq $0
	pushq $216
	jmp common
entry217:
	pushq $0
	pushq $217
	jmp common
entry218:
	pushq $0
	pushq $218
	jmp common
entry219:
	pushq $0
	pushq $219
	jmp common
entry220:
	pushq $0
	pushq $220
	jmp common
entry221:
	pushq $0
	pushq $221
	jmp common
entry222:
	pushq $0
	pushq $222
	jmp common
entry223:
	pushq $0
	pushq $223
	jmp common
entry224:
	pushq $0
	pushq $224
	jmp common
entry225:
	pushq $0
	pushq $225
	jmp common
entry226:
	pushq $0
	pushq $226
	jmp common
entry227:
	pushq $0
	pushq $227
	jmp common
entry228:
	pushq $0
	pushq $228
	jmp common
entry229:
	pushq $0
	pushq $229
	jmp common
entry230:
	pushq $0
	pushq $230
	jmp common
entry231:
	pushq $0
	pushq $231
	jmp common
entry232:
	pushq $0
	pushq $232
	jmp common
entry233:
	pushq $0
	pushq $233
	jmp common
entry234:
	pushq $0
	pushq $234
	jmp common
entry235:
	pushq $0
	pushq $235
	jmp common
entry236:
	pushq $0
	pushq $236
	jmp common
entry237:
	pushq $0
	pushq $237
	jmp common
entry238:
	pushq $0
	pushq $238
	jmp common
entry239:
	pushq $0
	pushq $239
	jmp common
entry240:
	pushq $0
	pushq $240
	jmp common
entry241:
	pushq $0
	pushq $241
	jmp common
entry242:
	pushq $0
	pushq $242
	jmp common
entry243:
	pushq $0
	pushq $243
	jmp common
entry244:
	pushq $0
	pushq $244
	jmp common
entry245:
	pushq $0
	pushq $245
	jmp common
entry246:
	pushq $0
	pushq $246
	jmp common
entry247:
	pushq $0
	pushq $247
	jmp common
entry248:
	pushq $0
	pushq $248
	jmp common
entry249:
	pushq $0
	pushq $249
	jmp common
entry250:
	pushq $0
	pushq $250
	jmp common
entry251:
	pushq $0
	pushq $251
	jmp common
entry252:
	pushq $0
	pushq $252
	jmp common
entry253:
	pushq $0
	pushq $253
	jmp common
entry254:
	pushq $0
	pushq $254
	jmp common
entry255:
	pushq $0
	pushq $255
	jmp common

common:
	pushq %rax
	pushq %rbx
	pushq %rcx
	pushq %rdx
	pushq %rbp
	pushq %rdi
	pushq %rsi
	pushq %r9
	pushq %r10
	pushq %r11
	pushq %r12
	pushq %r13
	pushq %r14
	pushq %r15
	movq %rsp, %rdi
	cld
	call handle
	popq %r15
	popq %r14
	popq %r13
	popq %r12
	popq %r11
	popq %r10
	popq %r9
	popq %rsi
	popq %rdi
	popq %rbp
	popq %rdx
	popq %rcx
	popq %rbx
	popq %rax
	addq $16, %rsp
	iretq

table:
	.quad entry0
	.quad entry1
	.quad entry2
	.quad entry3
	.quad entry4
	.quad entry5
	.quad entry6
	.quad entry7
	.quad entry8
	.quad entry9
	.quad entry10
	.quad entry11
	.quad entry12
	.quad entry13
	.quad entry14
	.quad entry15
	.quad entry16
	.quad entry17
	.quad entry18
	.quad entry19
	.quad entry20
	.quad entry21
	.quad entry22
	.quad entry23
	.quad entry24
	.quad entry25
	.quad entry26
	.quad entry27
	.quad entry28
	.quad entry29
	.quad entry30
	.quad entry31
	.quad entry32
	.quad entry33
	.quad entry34
	.quad entry35
	.quad entry36
	.quad entry37
	.quad entry38
	.quad entry39
	.quad entry40
	.quad entry41
	.quad entry42
	.quad entry43
	.quad entry44
	.quad entry45
	.quad entry46
	.quad entry47
	.quad entry48
	.quad entry49
	.quad entry50
	.quad entry51
	.quad entry52
	.quad entry53
	.quad entry54
	.quad entry55
	.quad entry56
	.quad entry57
	.quad entry58
	.quad entry59
	.quad entry60
	.quad entry61
	.quad entry62
	.quad entry63
	.quad entry64
	.quad entry65
	.quad entry66
	.quad entry67
	.quad entry68
	.quad entry69
	.quad entry70
	.quad entry71
	.quad entry72
	.quad entry73
	.quad entry74
	.quad entry75
	.quad entry76
	.quad entry77
	.quad entry78
	.quad entry79
	.quad entry80
	.quad entry81
	.quad entry82
	.quad entry83
	.quad entry84
	.quad entry85
	.quad entry86
	.quad entry87
	.quad entry88
	.quad entry89
	.quad entry90
	.quad entry91
	.quad entry92
	.quad entry93
	.quad entry94
	.quad entry95
	.quad entry96
	.quad entry97
	.quad entry98
	.quad entry99
	.quad entry100
	.quad entry101
	.quad entry102
	.quad entry103
	.quad entry104
	.quad entry105
	.quad entry106
	.quad entry107
	.quad entry108
	.quad entry109
	.quad entry110
	.quad entry111
	.quad entry112
	.quad entry113
	.quad entry114
	.quad entry115
	.quad entry116
	.quad entry117
	.quad entry118
	.quad entry119
	.quad entry120
	.quad entry121
	.quad entry122
	.quad entry123
	.quad entry124
	.quad entry125
	.quad entry126
	.quad entry127
	.quad entry128
	.quad entry129
	.quad entry130
	.quad entry131
	.quad entry132
	.quad entry133
	.quad entry134
	.quad entry135
	.quad entry136
	.quad entry137
	.quad entry138
	.quad entry139
	.quad entry140
	.quad entry141
	.quad entry142
	.quad entry143
	.quad entry144
	.quad entry145
	.quad entry146
	.quad entry147
	.quad entry148
	.quad entry149
	.quad entry150
	.quad entry151
	.quad entry152
	.quad entry153
	.quad entry154
	.quad entry155
	.quad entry156
	.quad entry157
	.quad entry158
	.quad entry159
	.quad entry160
	.quad entry161
	.quad entry162
	.quad entry163
	.quad entry164
	.quad entry165
	.quad entry166
	.quad entry167
	.quad entry168
	.quad entry169
	.quad entry170
	.quad entry171
	.quad entry172
	.quad entry173
	.quad entry174
	.quad entry175
	.quad entry176
	.quad entry177
	.quad entry178
	.quad entry179
	.quad entry180
	.quad entry181
	.quad entry182
	.quad entry183
	.quad entry184
	.quad entry185
	.quad entry186
	.quad entry187
	.quad entry188
	.quad entry189
	.quad entry190
	.quad entry191
	.quad entry192
	.quad entry193
	.quad entry194
	.quad entry195
	.quad entry196
	.quad entry197
	.quad entry198
	.quad entry199
	.quad entry200
	.quad entry201
	.quad entry202
	.quad entry203
	.quad entry204
	.quad entry205
	.quad entry206
	.quad entry207
	.quad entry208
	.quad entry209
	.quad entry210
	.quad entry211
	.quad entry212
	.quad entry213
	.quad entry214
	.quad entry215
	.quad entry216
	.quad entry217
	.quad entry218
	.quad entry219
	.quad entry220
	.quad entry221
	.quad entry222
	.quad entry223
	.quad entry224
	.quad entry225
	.quad entry226
	.quad entry227
	.quad entry228
	.quad entry229
	.quad entry230
	.quad entry231
	.quad entry232
	.quad entry233
	.quad entry234
	.quad entry235
	.quad entry236
	.quad entry237
	.quad entry238
	.quad entry239
	.quad entry240
	.quad entry241
	.quad entry242
	.quad entry243
	.quad entry244
	.quad entry245
	.quad entry246
	.quad entry247
	.quad entry248
	.quad entry249
	.quad entry250
	.quad entry251
	.quad entry252
	.quad entry253
	.quad entry254
	.quad entry255
